export enum CoreState {
  STOP = 'STOP',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  LOADING = 'LOADING',
  ERROR = 'ERROR'
}

export enum EventType {
  PLAY,
  PAUSE,
  STOP,
  SEEK,
  SET_VOLUME,
  SET_SPEED,
  SET_LOOP,
  SET_MUTED,
  SET_AUTOPLAY,
  SET_PLAYLIST,
  SET_CURRENT_TRACK,
  SET_CURRENT_TIME,
  SET_DURATION,
  SET_BUFFERED,
  SET_BUFFERING,
  SET_ERROR,
  SET_PLAYING,
  SET_PAUSED,
  TEST
}